name: Backend Deploy
on: { push: { branches: [ master ] } }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd MERNCICD/backend
            docker stop backend || true
            docker rm backend || true
            docker build -t backend .
            docker run -d -p 5000:5000 --env-file .env backend